version: "3.8"

services:
  # Pocketbase backend service
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - pocketbase_data:/pb_data
      - pocketbase_public:/pb_public
      - pb_migrations:/pb_migrations
    command: --migrationsDir=/pb_migrations --automigrate # Enable auto migrations
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8090/api/health || exit 1
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - app-network

  # Vite frontend service
  frontend:
    build:
      context: ./ # Path to your Vite app directory
      dockerfile: Dockerfile
    container_name: frontend
    restart: unless-stopped
    ports:
      - "80:80"
    depends_on:
      - pocketbase
    environment:
      - VITE_POCKETBASE_URL=http://pocketbase:8090
    networks:
      - app-network

volumes:
  pocketbase_data:
  pocketbase_public:
  pb_migrations:

networks:
  app-network:
    driver: bridge
